---
- name: Delete a workflow template
  ansible.controller.workflow_job_template:
    name: "patch-workflow-impl"
    organization: "midrange"
    state: absent
    tower_host: "{{ aap_host }}"
    tower_username: "{{ aap_username }}"
    tower_password: "{{ aap_password }}"


- name: Delete the set of job templates
  ansible.controller.job_template:
    name: "{{ item.name }}"
    organization: "midrange"
    inventory: "midrange-assets"
    state: absent
    tower_host: "{{ aap_host }}"
    tower_username: "{{ aap_username }}"
    tower_password: "{{ aap_password }}"
  loop:
    - { name: "1-create-cr" }
    - { name: "2-prepatch-check" }
    - { name: "4-apply-patch" }
    - { name: "5-postpatch-check" }
    - { name: "6-rollback-patch" }
    - { name: "3.0-update-cr-status-scheduled" }
    - { name: "3.1-update-cr-status-started" }
    - { name: "3.2-update-cr-status-failed" }
    - { name: "3.3-update-cr-status-review" }
    - { name: "3.4-update-cr-status-complete" }
    - { name: "patch-workflow" }

- name: Delete EDA application
  ansible.controller.application:
    name: "eda"
    organization: "midrange"
    state: absent
    tower_host: "{{ aap_host }}"
    tower_username: "{{ aap_username }}"
    tower_password: "{{ aap_password }}"

- name: Delete sample project
  ansible.controller.project:
    name: "itsm-demo"
    organization: "midrange"
    state: absent
    tower_host: "{{ aap_host }}"
    tower_username: "{{ aap_username }}"
    tower_password: "{{ aap_password }}"

- name: Delete sample credential
  ansible.controller.credential:
    name: "midrange-network-access"
    organization: "midrange"
    credential_type: Machine
    state: absent
    tower_host: "{{ aap_host }}"
    tower_username: "{{ aap_username }}"
    tower_password: "{{ aap_password }}"

- name: Delete sample inventory
  ansible.controller.inventory:
    name: "midrange-assets"
    organization: "midrange"
    state: absent
    tower_host: "{{ aap_host }}"
    tower_username: "{{ aap_username }}"
    tower_password: "{{ aap_password }}"

- name: Delete midrange Organization
  ansible.controller.organization:
    name: "midrange"
    state: absent
    tower_host: "{{ aap_host }}"
    tower_username: "{{ aap_username }}"
    tower_password: "{{ aap_password }}"
