---
# AAP Host Connection Information
aap_host: controller.localdomain
aap_username: admin
aap_password: password

# Name of a managed host to add to the sample organization Inventory
managed_host: dummy_host.rapid.net
