---
- name: Listen for Kafka events
  hosts: localhost
  sources:
    - name: Listen to Kafka server broker
      ansible.eda.kafka:
        topic: eda-topic
        host: eda-demo-kafka-brokers.aap.svc.cluster.local
        port: 9092
  rules:
    - name: Debug demo event
      condition: event.status == "enabled"
      action:
        run_job_template:
          name: "Demo Job Template"
