---
- name: Listen for Kafka events
  hosts: localhost
  sources:
    - name: Listen to Kafka server broker
      ansible.eda.kafka:
        topic: eda-topic
        host: 10.131.0.55
        port: 9092
        check_hostname: False
  rules:
    - name: Debug demo event
      condition: event.message != ""
      action:
        run_job_template:
          name: "Demo Job Template"
