---
- name: Listen for Kafka events
  hosts: localhost
  sources:
    - name: Listen to Kafka server broker
      ansible.eda.kafka:
        topic: eda-topic
        host: kafka-demo-kafka-bootstrap.aap.svc.cluster.local
        port: 9092
        check_hostname: False
  rules:
    - name: Debug demo event
      condition: event.message is defined
      action:
        debug:
          var: event
