---
- name: Watch for new incidents in ServiceNow
  hosts: localhost
  sources:
    - name: Listen to ServiceNow
      cloin.eda.snow_records:
        instance: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        table: incident
        interval: 1
  rules:
    - name: Debug everything
      condition: event.sys_id is defined
      action:
        debug:
          var: event
    - name: Debug everything else
      condition: event.sys_id is not defined
      action:
        debug:
          var: event
    - name: Augment incident
      condition: event.sys_id is defined
      action:
        run_job_template:
          organization: "midrange"
          name: "augment-incident"
