---
- name: Launch the patching workflow
  hosts: all
# NOTE: This is needed because EDA currently does not support
# launching a workflow job template as an action (only job
# templates).

  tasks:
    - name: Show me all the things
      ansible.builtin.debug:
        var: ansible_facts
    - name: Launch patching implementation workflow
      ansible.controller.workflow_launch:
        workflow_template: "patch-workflow-impl"
        controller_host: "{{ ansible_hostname }}"
