---
- name: Close SNow Change Request
  hosts: all

  tasks:
    - name: Update change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ snow_hostname }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"

        state: "{{ new_state }}"
        number: "{{ new_cr.number }}"
        assignment_group: "{{ assignment_group }}"
        close_code: "{{ close_code }}"
        close_notes: "{{ close_notes }}"
      register: new_cr
    - name: Show CR details
      ansible.builtin.debug:
        var: new_cr.diff.after

